### ISSUE TITLE
Could not locate configuration file: 'GoogleService-Info.plist'.

### ISSUE THREAD

**Issue by OkySabeni** [firebase/login-demo-ios#14]
I cloned the repo, ran the podfile, and run the project but I got a Could not locate configuration file: 'GoogleService-Info.plist'. error. How do I fix this?

The instruction on ViewController.m specifies "NOTE: You must configure Google by dragging "GoogleService-Info.plist" to "Supporting Files"." But I can't find a GoogleService-Info.plist file anywhere. 

Also, I have no intention of using google, facebook, or twitter login. I merely wanted to try the generic email/password login demo.

How do I get this resolved?

Thanks

**Comment by dxclancy** [comment]
The readme says "To setup Google auth, you'll need to create and add a GoogleService-Info.plist from here as well as configure a URL Scheme to match your Reversed Client ID."

**Comment by katfang** [comment]
If you're not interested in trying out Google Auth, you can also just not configure it and get around the error by opening up `AppDelegate.m` and commenting out these three lines:

    NSError* configureError;
    [[GGLContext sharedInstance] configureWithError: &configureError];
    NSAssert(!configureError, @"Error configuring Google services: %@", configureError);
