### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by carloshwa** [firebase/login-demo-ios#15]
I'm getting this error when I try to build the project:

    Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_Firebase", referenced from:
          objc-class-ref in ViewController.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have updated the project Podfile to use Firebase 2.4.1 and updated the target to iOS 8.4 and am using XCode 7.0.1.

**Comment by jdimond** [comment]
This is due to a broken release for Firebase on CocoaPods. We're working on a fix for that. As a workaround until we release that you can point to 2.3.3 in the Podfile.
