### ISSUE TITLE
iOS getting several errors around "ACAccount" and "Bad receiver type int'

### ISSUE THREAD

**Issue by swells808** [firebase/login-demo-ios#16]
Downloaded the demo file for iOS, ran the podfile install, and upon compiling I am getting several errors that seem to point at anything with the ACAccount property. For example:

@property (strong, nonatomic) ACAccount *store;

Renders the error "Unknown type name 'ACAccountStore' " Why is this?

**Comment by joejoecc** [comment]
I'm getting this same error.  I'm running Xcode 7.2

![screen shot 2016-02-17 at 4 52 55 pm](https://cloud.githubusercontent.com/assets/1912100/13130183/ffd4e2f4-d596-11e5-8d6c-1eb8e5d330e2.png)
](url)

**Comment by Klikur** [comment]
I am also getting the same errors.

**Comment by katfang** [comment]
It appears to have to do with modules. Change the imports in TwitterAuthHelper.h from


    @import Accounts;

To the top of the TwitterAuthHelper.h class right under

    #import <Firebase/Firebase.h>

 and this should

**Comment by katfang** [comment]
It has to do with Xcode modules. You can fix this by changing the imports in `TwitterAuthHelper.h` from

    #import <Firebase/Firebase.h>

to

    #import <Firebase/Firebase.h>
    @import Accounts;

Not sure about the back-compat of the the new modules stuff, so here's the work around, and I'll look into landing an actual fix in the repo.

**Comment by abehaskins** [comment]
Hi!

This is example is super old and no longer maintained. You should check out a more up-to-date example like [FriendlyChat](https://github.com/firebase/friendlychat) for how to get started!

Allt he best,
abe
