### ISSUE TITLE
Error: Please add "GoogleService-Info.plist' to 'Support Files'

### ISSUE THREAD

**Issue by silverj93** [firebase/login-demo-ios#19]
I am getting an error with the following line of code:
![image](https://cloud.githubusercontent.com/assets/6836522/14004930/7114f928-f134-11e5-945d-c252fa4c34de.png)

I have added "GoogleService-Info.plist" to the support files and have Info.plist as required.

![image](https://cloud.githubusercontent.com/assets/6836522/14004986/d0931b32-f134-11e5-9857-85a7c7a1d01c.png)

**Comment by abehaskins** [comment]
Hi!

This is example is super old and no longer maintained. You should check out a more up-to-date example like [FriendlyChat](https://github.com/firebase/friendlychat) for how to get started!

Allt he best,
abe
