### ISSUE TITLE
Several IOS errors 

### ISSUE THREAD

**Issue by asad-awadia** [firebase/login-demo-ios#21]
Downloaded the file - Ran pod install - Tried compiling it but getting several errors..
![screen shot 2016-04-26 at 1 59 25 pm](https://cloud.githubusercontent.com/assets/6923282/14828997/69c4f9c8-0bb7-11e6-883a-45af1f34fb35.png)

**Comment by abehaskins** [comment]
Hi!

This is example is super old and no longer maintained. You should check out a more up-to-date example like [FriendlyChat](https://github.com/firebase/friendlychat) for how to get started!

Allt he best,
abe
