### ISSUE TITLE
Will not allow me to use a "Firebase" instance.

### ISSUE THREAD

**Issue by jamesesterbrookerwin** [firebase/login-demo-ios#23]
this has been driving me crazy. I used #import <Firebase/Firebase.h> and @import Firebase and the compiler still gives me an "unknown type name" error. I have no idea what could possibly be the problem. I don't think I accidentally created an type of cycle. Please help.

**Comment by jamesesterbrookerwin** [comment]
Little more info: i installed the firebase pod on my Podfile. Tried #import <Firebase/Firebase.h>, and @import Firebase;. Neither worked, and I'm stuck

**Comment by ihniwgo** [comment]
Did you ever get past this? I am having the same trouble after updating to 3.6.0

**Comment by abehaskins** [comment]
Hi folks,

This example is super old and uses a legacy (non-3.* compatible) SDK so you should check out a more up-to-date example like [FriendlyChat](https://github.com/firebase/friendlychat) for how to use auth!

Allt he best,
abe
